title: enginR | Blog and personal portfolio by Abishek Kumar
title_name: enginR
description: >- # this means to ignore newlines until "baseurl:"
  enginR is a web portal for blogging and portfolio built with jekyll. The blog posts present here are self written and published.

url: "https://realnighthawk.me" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact
    # - text: Resume
    #   url : /resume

# Edit these details

author_logo: profile.png
author: Abishek Kumar
author_desc: Site Reliability Engineer / Developer
author_bio: Hi, my name is Abishek Kumar. I built this site using jekyll :D
author_email: "abishekkumar92@gmail.com"
author_location: India
author_website_url: "http://realnighthawk.me"
typewrite-text: Feel free to explore my personal blog and portfolio.

author_work_experiences:
            - company_name: Bookmyshow
              company_logo: bms.png
              company_url: https://bookmyshow.com
              designation: Site Reliability Engineer
              description: Worked on various Infrastructure tooling
              visibility: true

author_education_details:
              - college_logo: iit.png
                college_name: IIT Indore
                college_url: https://www.iiti.ac.in/
                college_degree: Electrical Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: abd_abishek
github_username:  kumarabd
facebook_username: abishekkumar92
linkedin_username: kumarabd
instagram_username: abishek_it_is
medium_username: abishekkumar92
telegram_username: hu1kbu5t3r
flickr_username: abishekkumar92

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: 

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# # Gallery
# defaults:
#   -
#     scope:
#       path: "gallery"
#     values:
#       permalink: /:path/:basename:output_ext


# SEO parameters
tagline: Every engineer has his own story
twitter:
  username: abd_abishek
  card: summary
logo: /assets/img/profile.png
social:
  name: Abishek Kumar
  links:
    - https://twitter.com/abd_abishek
    - https://www.facebook.com/abishekkumar92
    - https://www.linkedin.com/in/kumarabd
    - https://github.com/kumarabd
lang: en-us

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
